name: Deploy to Railway

on:
  push:
    branches:
      - main # Sesuaikan dengan branch utama Anda, misalnya 'main' atau 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # Install Railway CLI
          curl -fsSL https://railway.app/install.sh | sh

          # Verifikasi versi Railway CLI
          railway --version

          # Deploy project
          railway up -- --auto-accept
