name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          curl -sL https://raw.githubusercontent.com/railwayapp/cli/main/install.sh | sh
          echo "export PATH=\"$HOME/.railway/bin:$PATH\"" >> $GITHUB_ENV

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up
