name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          # Install Railway CLI
          curl -fsSL https://railway.app/install.sh | sh

          # Verifikasi Railway CLI terinstal
          railway --help

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # Deploy project
          railway up --auto-accept
